refactor: Update to use deepCopy of messageBusInfo to avoid external adds
edgexfoundry/device-sdk-go pull request #1166
Opened 2022-05-24 10:33 UTC by jinlinGuan

fix #1162

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) update the existing unit test
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

1. Build device-virtual docker image from this branch and run the security-enabled docker compose
2. GET `/api/v2/config` and verify the response
## New Dependency Instructions (If applicable)

2022-05-24 13:57 UTC, cloudxxx8 requested changes

2022-05-24 13:57 UTC, cloudxxx8 commented on internal/messaging/messaging_test.go
> +			assert.Empty(t,test.Config.MessageQueue.Optional)
there is a fmt issue in messaging_test.go
it looks like you need a space in this line
please make sure `make test` can pass

2022-05-24 15:22 UTC, lenny-intel approved these changes
LGTM once fmt issue resolved.

2022-05-25 01:23 UTC, cloudxxx8 approved these changes
LGTM

2022-05-25 01:43 UTC, merged