refactor: use bootstrap handlers in go-mod-bootstrap and refactor device command application layer code
edgexfoundry/device-sdk-go pull request #1210
Opened 2022-09-16 08:36 UTC by hahattan

related to #1189, refactored device command application layer so we have better API to use in internal message bus subscriber.

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-09-19 21:33 UTC, lenny-intel requested changes

2022-09-19 21:33 UTC, lenny-intel commented on pkg/service/main.go
> +func MessageBusBootstrapHandler(ctx context.Context, wg *sync.WaitGroup, startupTimer startup.Timer, dic *di.Container) bool {
Should this be private functions since they are only called from above.

2022-09-19 21:33 UTC, lenny-intel commented on internal/application/command.go
> +	lc.Infof("GET Device Command successfully. Device: %s, Source: %s, %s: %s", deviceName, commandName, common.CorrelationHeader, utils.FromContext(ctx, common.CorrelationHeader))
```suggestion
	lc.Debugf("GET Device Command successfully. Device: %s, Source: %s, %s: %s", deviceName, commandName, common.CorrelationHeader, utils.FromContext(ctx, common.CorrelationHeader))
```

2022-09-19 21:33 UTC, lenny-intel commented on internal/application/command.go
> +	lc.Infof("SET Device Command successfully. Device: %s, Source: %s, %s: %s", deviceName, commandName, common.CorrelationHeader, utils.FromContext(ctx, common.CorrelationHeader))
```suggestion
	lc.Debugf("SET Device Command successfully. Device: %s, Source: %s, %s: %s", deviceName, commandName, common.CorrelationHeader, utils.FromContext(ctx, common.CorrelationHeader))
```

2022-09-20 18:20 UTC, lenny-intel approved these changes
LGTM, just need to address the conflicts

2022-09-21 00:26 UTC, lenny-intel submitted a review, later dismissed

2022-09-21 00:27 UTC, lenny-intel commented
@hahattan , still have conflicts to resolve.

2022-09-21 02:05 UTC, hahattan commented
recheck

2022-09-21 05:16 UTC, cloudxxx8 approved these changes
LGTM

2022-09-21 05:16 UTC, cloudxxx8 commented
recheck

2022-09-21 06:35 UTC, merged