feat: Add resource, command, and device tags to reading/event
edgexfoundry/device-sdk-go pull request #1297
Opened 2023-01-31 07:06 UTC by FelixTing

fix #1294 

1. Add device resource tags to reading
2. Add device command tags to event
3. Add device tags to event
Note: Device tags take precedence over Device Command tags.

Signed-off-by: Felix Ting <felix@iotechsys.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) need integration tests due to the use of Device and Profile caches
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

1. Run non-secure EdgeX Stack
2. Based on this branch, modify the device configuration of Device Simple to add device tags

simple-device.toml
```
[[DeviceList]]
  Name = "Simple-Device01"
  ProfileName = "Simple-Device"
  Description = "Example of Simple Device"
  Labels = [ "industrial" ]
  [DeviceList.Tags]
    deviceTag = "deviceTag"
  [DeviceList.Protocols]
  [DeviceList.Protocols.other]
    Address = "simple01"
    Port = "300"
  [[DeviceList.AutoEvents]]
    Interval = "10s"
    OnChange = false
    SourceName = "Switch"
  [[DeviceList.AutoEvents]]
    Interval = "30s"
    OnChange = false
    SourceName = "Image"
```

3. Modify the device profile configuration of Device Simple to add resource and command tags

Simple-Driver.yaml
```
apiVersion: "v2"
name: "Simple-Device"
manufacturer: "Simple Corp."
model: "SP-01"
labels:
  - "modbus"
description: "Example of Simple Device"

deviceResources:
  -
    name: "SwitchButton"
    isHidden: false
    description: "Switch On/Off."
    tags:
      resourceTag: "resourceTag"
    properties:
        valueType: "Bool"
        readWrite: "RW"
        defaultValue: "true"
  -
    name: "Image"
    isHidden: false
    description: "Visual representation of Switch state."
    properties:
        valueType: "Binary"
        readWrite: "R"
        mediaType: "image/jpeg"
  -
    name: "Xrotation"
    isHidden: true
    description: "X axis rotation rate"
    properties:
        valueType: "Int32"
        readWrite: "RW"
        units: "rpm"
  -
    name: "Yrotation"
    isHidden: true
    description: "Y axis rotation rate"
    properties:
        valueType: "Int32"
        readWrite: "RW"
        "units": "rpm"
  -
    name: "Zrotation"
    isHidden: true
    description: "Z axis rotation rate"
    properties:
        valueType: "Int32"
        readWrite: "RW"
        "units": "rpm"
  -
    name: "StringArray"
    isHidden: false
    description: "String array"
    properties:
      valueType: "StringArray"
      readWrite: "RW"
  -
    name: "Uint8Array"
    isHidden: false
    description: "Unsigned 8bit array"
    properties:
        valueType: "Uint8Array"
        readWrite: "RW"
  -
    name: "Counter"
    isHidden: false
    description: "Counter data"
    properties:
      valueType: "Object"
      readWrite: "RW"

deviceCommands:
  -
    name: "Switch"
    isHidden: false
    readWrite: "RW"
    tags:
      commandTag: "commandTag"
    resourceOperations:
      - { deviceResource: "SwitchButton", defaultValue: "false" }
  -
    name: "Image"
    isHidden: false
    readWrite: "R"
    resourceOperations:
      - { deviceResource: "Image" }
  -
    name: "Rotation"
    isHidden: false
    readWrite: "RW"
    resourceOperations:
      - { deviceResource: "Xrotation", defaultValue: "0" }
      - { deviceResource: "Yrotation", defaultValue: "0" }
      - { deviceResource: "Zrotation", defaultValue: "0" }

```

4. Run Device Simple
5. `curl http://localhost:59882/api/v2/device/name/Simple-Device01/Switch`
Verify the returned event contains resource, command, and device tags.
```
{
    "apiVersion": "v2",
    "statusCode": 200,
    "event": {
        "apiVersion": "v2",
        "id": "de6e7c7c-5cb3-4af6-b3ac-3d0c460fe211",
        "deviceName": "Simple-Device01",
        "profileName": "Simple-Device",
        "sourceName": "Switch",
        "origin": 1675147339613147000,
        "readings": [
            {
                "id": "98bf94c7-6a9b-45a6-a2a9-f7c976728c8c",
                "origin": 1675147339613147000,
                "deviceName": "Simple-Device01",
                "resourceName": "SwitchButton",
                "profileName": "Simple-Device",
                "valueType": "Bool",
                "tags": {
                    "resourceTag": "resourceTag"
                },
                "value": "false"
            }
        ],
        "tags": {
            "commandTag": "commandTag",
            "deviceTag": "deviceTag"
        }
    }
}
```

## New Dependency Instructions (If applicable)

2023-01-31 20:29 UTC, lenny-intel requested changes
LGTM, just need to add missing unit tests

2023-01-31 20:29 UTC, lenny-intel commented on internal/common/utils.go
> +}
Please add unit tests

2023-02-01 17:42 UTC, FelixTing commented on internal/common/utils.go
> +}
added unit tests

2023-02-01 23:30 UTC, lenny-intel approved these changes
LGTM

2023-02-06 11:30 UTC, cloudxxx8 commented
@FelixTing please resolve the conflict

2023-02-06 14:31 UTC, FelixTing commented
rebased

2023-02-06 15:30 UTC, FelixTing commented
all unit tests have passed

2023-02-06 16:16 UTC, lenny-intel approved these changes
LGTM

2023-02-06 16:16 UTC, merged