feat: publish event with updated value for PUT command
edgexfoundry/device-sdk-go pull request #1356
Opened 2023-03-03 09:37 UTC by hahattan

Similiar to GET command with 'ds-pushevent=true', publish an event with updated resource(s) value to messageBus as long as the resource/command is not write-only.

closes #1271

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

1. Run `device-simple` from this branch
2. Subscribe to edgex internal event topics in `redis` container:
```shell
# docker exec -it edgex-redis /bin/sh
/data # redis-cli
127.0.0.1:6379> PSUBSCRIBE edgex.events.device.*
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "edgex.events.device.*"
3) (integer) 1
1) "pmessage"
2) "edgex.events.device.*"
3) "edgex.events.device.device-simple.Simple-Device.Simple-Device01.Xrotation"
4) "{\"ReceivedTopic\":\"\",\"CorrelationID\":\"24683755-b598-4dda-8f3e-29536ef2b3d6\",\"ApiVersion\":\"v2\",\"RequestID\":\"\",\"ErrorCode\":0,\"Payload\":\"eyJhcGlWZXJzaW9uIjoidjIiLCJyZXF1ZXN0SWQiOiJkODZjOTliOS1iMGE0LTQ2MzgtODgxOS03ODAxYTJjZTA4ZWUiLCJldmVudCI6eyJhcGlWZXJzaW9uIjoidjIiLCJpZCI6ImM1ZDllN2E4LWE3NzEtNGNkNS04NTBmLTU4OTJhMDIxNDE1NiIsImRldmljZU5hbWUiOiJTaW1wbGUtRGV2aWNlMDEiLCJwcm9maWxlTmFtZSI6IlNpbXBsZS1EZXZpY2UiLCJzb3VyY2VOYW1lIjoiWHJvdGF0aW9uIiwib3JpZ2luIjoxNjc3ODM1Nzc1NTcyNzMwMDAwLCJyZWFkaW5ncyI6W3siaWQiOiIxMTRlZGNmYS1hNTAwLTRmMGEtYTBkMC02MTNlZDU5ZWYyZGQiLCJvcmlnaW4iOjE2Nzc4MzU3NzU1NzI3MzAwMDAsImRldmljZU5hbWUiOiJTaW1wbGUtRGV2aWNlMDEiLCJyZXNvdXJjZU5hbWUiOiJYcm90YXRpb24iLCJwcm9maWxlTmFtZSI6IlNpbXBsZS1EZXZpY2UiLCJ2YWx1ZVR5cGUiOiJJbnQzMiIsInVuaXRzIjoicnBtIiwidmFsdWUiOiIxMCJ9XX19\",\"ContentType\":\"application/json\",\"QueryParams\":{}}"
```
3. Verify there's an event being published after a successfully PUT command:
```shell
# curl -X PUT -H "Content-Type: application/json" -d '{"Xrotation": "10"}' http://localhost:59882/api/v2/device/name/Simple-Device01/Xrotation
{"apiVersion":"v2","statusCode":200}
```

base64 decode the payload:
```json
{
   "apiVersion":"v2",
   "requestId":"d86c99b9-b0a4-4638-8819-7801a2ce08ee",
   "event":{
      "apiVersion":"v2",
      "id":"c5d9e7a8-a771-4cd5-850f-5892a0214156",
      "deviceName":"Simple-Device01",
      "profileName":"Simple-Device",
      "sourceName":"Xrotation",
      "origin":1677835775572730000,
      "readings":[
         {
            "id":"114edcfa-a500-4f0a-a0d0-613ed59ef2dd",
            "origin":1677835775572730000,
            "deviceName":"Simple-Device01",
            "resourceName":"Xrotation",
            "profileName":"Simple-Device",
            "valueType":"Int32",
            "units":"rpm",
            "value":"10"
         }
      ]
   }
}
```

Note that this behavior also applies to commands via messaging.

## New Dependency Instructions (If applicable)

2023-03-08 15:51 UTC, lenny-intel requested changes

2023-03-08 15:51 UTC, lenny-intel commented on internal/application/command.go
> +	res, edgexErr = transformer.CommandValuesToEventDTO(results, device.Name, dr.Name, configuration.Device.DataTransform, dic)
I am confused on why readDeviceResource is being changed for PR that is about Set.
Is this change for `DataTransform` in scope for what this PR is for? If so, why?

2023-03-08 15:51 UTC, lenny-intel commented on internal/application/command.go
> +	res, edgexErr = transformer.CommandValuesToEventDTO(results, device.Name, dc.Name, configuration.Device.DataTransform, dic)
Same question here about scope of the PR?

2023-03-08 15:51 UTC, lenny-intel commented on internal/application/command.go
> +	// from EdgeX3.0, updated resource value will be published to messageBus as long as
Code is on 3.0 branch so no need to state this.

```suggestion
	// Updated resource value will be published to MessageBus as long as
```

2023-03-08 15:51 UTC, lenny-intel commented on internal/application/command.go
> +	// from EdgeX3.0, updated resource(s) value will be published to messageBus as long as
```suggestion
	// Updated resource(s) value will be published to MessageBus as long as
```

2023-03-08 20:35 UTC, lenny-intel commented on internal/application/command.go
> +	res, edgexErr = transformer.CommandValuesToEventDTO(results, device.Name, dr.Name, configuration.Device.DataTransform, dic)
OK, thanks for the explination.

2023-03-09 03:20 UTC, lenny-intel submitted a review, later dismissed
LGTM

2023-03-09 03:46 UTC, hahattan commented
rebased and resolved conflict

2023-03-13 03:56 UTC, cloudxxx8 requested changes

2023-03-13 03:56 UTC, cloudxxx8 commented on internal/transformer/transform.go
> +		if dataTransform {
modify line 50 from
`readings := make([]dtos.BaseReading, 0, config.Device.MaxCmdOps)`
to 
`readings := make([]dtos.BaseReading, 0, len(cvs))`

then, we can remove the `config` from this function for good.  I forget the reason we used `config.Device.MaxCmdOps` in the first place.  It seems a wrong usage.

2023-03-13 04:26 UTC, cloudxxx8 approved these changes
LGTM

2023-03-13 07:00 UTC, cloudxxx8 requested changes

2023-03-13 07:00 UTC, cloudxxx8 commented on internal/controller/http/command.go
> +		go sdkCommon.SendEvent(event, correlationId, c.dic)
check reserved[common.PushEvent] and reserved[common.ReturnEvent] to decide how to response the result

2023-03-13 07:00 UTC, cloudxxx8 commented on internal/controller/http/command.go
> +	event, err := application.SetCommand(ctx, deviceName, commandName, queryParams, requestParamsMap, c.dic)
modify the swagger file for this API enhanchement as well

2023-03-13 07:05 UTC, cloudxxx8 commented on internal/controller/http/command.go
> +		go sdkCommon.SendEvent(event, correlationId, c.dic)
I misunderstood the requrement, resolving this change request

2023-03-13 07:07 UTC, cloudxxx8 commented on internal/controller/http/command.go
> +	event, err := application.SetCommand(ctx, deviceName, commandName, queryParams, requestParamsMap, c.dic)
add a statment in the description
https://github.com/edgexfoundry/device-sdk-go/blob/84b3eaa6b9d9b6bc9df706aeb119f986429132ec/openapi/v3/device-sdk.yaml#L437

2023-03-13 13:23 UTC, cloudxxx8 commented on internal/controller/http/command.go
> +	event, err := application.SetCommand(ctx, deviceName, commandName, queryParams, requestParamsMap, c.dic)
since the docs PR is opened, resolving this change request

2023-03-13 13:23 UTC, cloudxxx8 approved these changes
LGTM

2023-03-13 13:23 UTC, merged