Update V2 Swagger file callback API status code
edgexfoundry/device-sdk-go pull request #595
Opened 2020-09-21 03:24 UTC by jinlinGuan

fix https://github.com/edgexfoundry/device-sdk-go/issues/555

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines#CommittingCodeGuidelines-CommitMessages
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:
#555 

## What is the new behavior?
update v2 swagger callback API status code from 200 to 204, add 404 for PUT request, and change 400 to 404 for DELETE request

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?
no
## Are there any specific instructions or things that should be known prior to reviewing?
no
## Other information

2020-09-21 03:30 UTC, cloudxxx8 commented
@iain-anderson to be consist with edgex-go V2 API, we modify the status code of callback.
please help confirm whether it is ok with you, and it should be consistent in C SDK.
Basically, we change 200 to 204 because there is no content replied in callback if it is successful.

2020-09-21 11:22 UTC, iain-anderson submitted a review, later dismissed
Fine with this.
I think in practice the 404 returns on the update calls won't happen: the device service will create the object and return 204.

2020-09-21 11:38 UTC, cloudxxx8 commented
> Fine with this.
> I think in practice the 404 returns on the update calls won't happen: the device service will create the object and return 204.

It was not a requirement.  If you can confirm we could allow to create a new one by Put, we can make it in V2.

2020-09-28 15:58 UTC, cloudxxx8 requested changes
the `type` field in the Reading schema should be `valueType`

2020-09-29 17:53 UTC, lenny-intel approved these changes
LGTM

2020-10-05 01:48 UTC, jinlinGuan commented
> the `type` field in the Reading schema should be `valueType`

Changed and reabased.

2020-10-05 05:13 UTC, cloudxxx8 approved these changes
LGTM

2020-10-05 05:13 UTC, merged