feat: implement v2 discovery API
edgexfoundry/device-sdk-go pull request #603
Opened 2020-09-30 05:45 UTC by hahattan

Signed-off-by: Chris Hung <chris@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines#CommittingCodeGuidelines-CommitMessages
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

2020-09-30 23:23 UTC, lenny-intel submitted a review, later dismissed
LGTM, but swagger indicates a `500` status, which I don't see a case for. Should this `500` status be removed from the swagger?

2020-10-05 06:33 UTC, cloudxxx8 commented
@lenny-intel I would prefer to keep `500` status code.  It covers all unknown internal error, and we might reply it in the future.
On the other hand, the Swagger API definition is for all kinds of Device Service implementation, so `500` might be returned by device services implemented in other technologies.

2020-10-05 06:46 UTC, hahattan commented
rebased

2020-10-05 19:25 UTC, lenny-intel commented
> I would prefer to keep `500` status code. It covers all unknown internal error, and we might reply it in the future.
> On the other hand, the Swagger API definition is for all kinds of Device Service implementation, so `500` might be returned by device services implemented in other technologies.

@hahattan , just note that TAF team will use the swagger to determine error tests and will expect to create a Test Case that triggers the 500 status code. Also, the SDks (Go & C) should be consistent on what triggers each status code, i.e. C SDK shouldn't return a 500 when the Go SDK returns something else for the same input.

2020-10-05 19:25 UTC, lenny-intel approved these changes

2020-10-06 04:53 UTC, cloudxxx8 commented
> > I would prefer to keep `500` status code. It covers all unknown internal error, and we might reply it in the future.
> > On the other hand, the Swagger API definition is for all kinds of Device Service implementation, so `500` might be returned by device services implemented in other technologies.
> 
> @cloudxxx8 , just note that TAF team will use the swagger to determine error tests and will expect to create a Test Case that triggers the 500 status code. Also, the SDks (Go & C) should be consistent on what triggers each status code, i.e. C SDK shouldn't return a 500 when the Go SDK returns something else for the same input.

@lenny-intel the QA team could only test 4XX negative test cases.  5XX should not be produced by the requests.

2020-10-06 05:41 UTC, cloudxxx8 requested changes

2020-10-06 05:41 UTC, cloudxxx8 commented on internal/v2/controller/http/discovery.go
> +	if ds.OperatingState == contract.Disabled {
In V2 API, we decided to remove OperatingState from Device Service, so please remove this section

2020-10-06 06:14 UTC, cloudxxx8 approved these changes
LGTM

2020-10-06 06:14 UTC, merged

2020-10-11 06:15 UTC, cloudxxx8 commented
> @cloudxxx8 , just note that TAF team will use the swagger to determine error tests and will expect to create a Test Case that triggers the 500 status code. Also, the SDks (Go & C) should be consistent on what triggers each status code, i.e. C SDK shouldn't return a 500 when the Go SDK returns something else for the same input.

If the error is caused by any middleware layer, such as header manipulating, or third party http library, such as gorilla mux although possibility is small, it would become 500 and we can't control it.  I thought we should always leave 500 internal error in each API definition.