refactor(sdk): release lock after discovery complete
edgexfoundry/device-sdk-go pull request #624
Opened 2020-10-08 13:00 UTC by hahattan

Add a wrapper function to call discovery.Discovery() and release the
lock when call completed so that developer will not be forced to push
something to deviceCh to release the lock

Signed-off-by: Chris Hung <chris@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines#CommittingCodeGuidelines-CommitMessages
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

Issue Number:
fix #609

2020-10-08 13:22 UTC, iain-anderson requested changes

2020-10-08 13:22 UTC, iain-anderson commented on internal/autodiscovery/discovery.go
> +	if locker.busy {
Think you need to Lock() before this `if`

2020-10-08 16:17 UTC, iain-anderson approved these changes

2020-10-11 07:13 UTC, cloudxxx8 approved these changes
LGTM

2020-10-11 07:13 UTC, merged