test/docs(sdk): update README and add unit tests
edgexfoundry/device-sdk-go pull request #637
Opened 2020-10-21 03:09 UTC by hahattan

add unit tests for ProvisionWatcher filter logic as a baseline for
each scenario and update the README about the ProvisionWatcher.

Signed-off-by: Chris Hung <chris@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines#CommittingCodeGuidelines-CommitMessages
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

2020-10-21 18:16 UTC, lenny-intel requested changes

2020-10-21 18:16 UTC, lenny-intel commented on example/README.md
> +A candidate new device passes a ProvisionWatcher if all of the Intifiers match, and none of the BlockingIdentifiers.
change `Intifiers` to `Identifiers` and `BlockingIdentifiers` to `Blocking Identifiers match`

2020-10-22 16:43 UTC, lenny-intel submitted a review, later dismissed
LGTM, @cloudxxx8 ?

2020-10-23 01:53 UTC, hahattan commented
rebased

2020-10-23 10:28 UTC, cloudxxx8 approved these changes
LGTM

2020-10-23 10:28 UTC, merged