ci: update docker image name
edgexfoundry/device-sdk-go pull request #725
Opened 2021-01-11 21:16 UTC by ernestojeda

Even though the docker image is not pushed, this PR removes `docker-` prefix from docker image name for consistency with other projects.

Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-c/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

## Issue Number:

## What is the new behavior?
New image name

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions

## Other information

2021-02-01 05:29 UTC, cloudxxx8 approved these changes
LGTM

2021-02-01 05:30 UTC, cloudxxx8 requested changes
Please also modify the Makefile
https://github.com/edgexfoundry/device-sdk-go/blob/3aea893206dfece0cb943228d650ae216607898f/Makefile#L27-L28

2021-05-11 17:00 UTC, ernestojeda commented
> Please also modify the Makefile
> https://github.com/edgexfoundry/device-sdk-go/blob/3aea893206dfece0cb943228d650ae216607898f/Makefile#L27-L28

This is now done

2021-05-11 17:03 UTC, lenny-intel approved these changes
LGTM

2021-05-11 17:19 UTC, merged