refactor: Update go-mod-bootstrap version to use latsest config
edgexfoundry/device-sdk-go pull request #949
Opened 2021-05-27 22:36 UTC by jim-wang-intel

Latest config on SecretStore section with removal of retry-related items and secret path update

Closes: #948
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-c/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

With retry items and secret path full

## Issue Number: #948 

## What is the new behavior?
No more retry properties or items from SecreStore config section and update the secret path to be service specific

## Does this PR introduce a breaking change?

- [x ] Yes
- [ ] No

**Note: all the toml files with these retry item or properties need to be updated: `AdditionalRetryAttempts`, `RetryWaitPeriod`
and the Path property changed to just contain the service specific item as the prefix `/v1/secret/edgex/` is now automatically added in front of it.**

## New Imports

- [ ] Yes
- [x ] No

## Specific Instructions

## Other information

2021-05-28 05:49 UTC, cloudxxx8 requested changes
configuration.toml should also be modified
https://github.com/edgexfoundry/device-sdk-go/blob/f9e550b20f5a93948f1e6d0294bcd4043c76663f/example/cmd/device-simple/res/configuration.toml#L66-L72

2021-06-01 15:35 UTC, jim-wang-intel commented
> configuration.toml should also be modified
> https://github.com/edgexfoundry/device-sdk-go/blob/f9e550b20f5a93948f1e6d0294bcd4043c76663f/example/cmd/device-simple/res/configuration.toml#L66-L72

Thanks, @cloudxxx8  good catch, I didn't know there is example config here. I'll fix that.

2021-06-01 15:56 UTC, jim-wang-intel commented
Config file fixed, @cloudxxx8. Thanks!

2021-06-01 17:59 UTC, lenny-intel approved these changes

2021-06-01 18:00 UTC, merged